name: Package Action

permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - staging
      - beta

jobs:
  package-action:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Package Action
        run: |
          npm i 
          npm run build
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "chore: Update dist" || echo "No changes to commit"
          git push
